INSERT INTO `user` (`username`, `password`, `email`) VALUES
('user1', 'password1', 'user1@example.com'),
('user2', 'password2', 'user2@example.com'),
('user3', 'password3', 'user3@example.com'),
('user4', 'password4', 'user4@example.com'),
('user5', 'password5', 'user5@example.com'),
('user6', 'password6', 'user6@example.com'),
('user7', 'password7', 'user7@example.com'),
('user8', 'password8', 'user8@example.com'),
('user9', 'password9', 'user9@example.com'),
('user10', 'password10', 'user10@example.com'),
('user11', 'password11', 'user11@example.com'),
('user12', 'password12', 'user12@example.com'),
('user13', 'password13', 'user13@example.com'),
('user14', 'password14', 'user14@example.com'),
('user15', 'password15', 'user15@example.com'),
('user16', 'password16', 'user16@example.com'),
('user17', 'password17', 'user17@example.com'),
('user18', 'password18', 'user18@example.com'),
('user19', 'password19', 'user19@example.com'),
('user20', 'password20', 'user20@example.com'),
('user21', 'password21', 'user21@example.com'),
('user22', 'password22', 'user22@example.com'),
('user23', 'password23', 'user23@example.com'),
('user24', 'password24', 'user24@example.com'),
('user25', 'password25', 'user25@example.com');

-- Insert test data into the tickets table
INSERT INTO `ticket` (`ticketname`, `status`) VALUES
('ticket1', 'open'),
('ticket2', 'closed'),
('ticket3', 'in progress'),
('ticket4', 'open'),
('ticket5', 'closed'),
('ticket6', 'open'),
('ticket7', 'in progress'),
('ticket8', 'closed'),
('ticket9', 'open'),
('ticket10', 'closed'),
('ticket11', 'open'),
('ticket12', 'closed'),
('ticket13', 'open'),
('ticket14', 'closed'),
('ticket15', 'open'),
('ticket16', 'closed'),
('ticket17', 'open'),
('ticket18', 'closed'),
('ticket19', 'open'),
('ticket20', 'closed');